@ECHO ีออออออออออออออออออออออออออออออออออออออออออธ
@ECHO ณ                                          ณ
@ECHO ณ  R o b o   H E L P                  ฐ ฐ  ณ
@ECHO ณ ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ              ฐ ฐ ฐ ฐ ณ
@ECHO ณ  Make Help Project              ฐ ฐฐฐ ฐ ฐณ
@ECHO ณ                                  ฐ ฐฐฐ  ฐณ
@ECHO ณ                                 ฐ ฐ  ฐฐ  ณ
@ECHO ณ                                  ฐ ฐ  ฐฐ ณ
@ECHO ณ                                       ฐฐฐณ
@ECHO ณ B L U E   S K Y   S O F T W A R E      ฐฐณ
@ECHO ณ                                        ฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐฐฐฐฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐณ
@ECHO ิออออออออออออออออออออออออออออออออออออออออออพ
@ECHO Batch File: D:\APPS\INTERNET\INETNAV\HLP\RHHC.BAT
@ECHO Project File: D:\APPS\INTERNET\INETNAV\HLP\INETNAV.hpj
del INETNAV.err

if (%TMP%)==() set TMP=%TEMP%
if (%TMP%)==() set TMP=C:\

C:\WINHELP\ROBOHELP\HCP.EXE INETNAV.hpj


