//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Inetnav.rc
//
#define IDR_MAINFRAME                   2
#define IDR_FINGERTYPE                  3
#define IDR_WHOISTYPE                   4
#define IDR_FTPTYPE                     5
#define IDR_MAINMENUTYPE                6
#define IDR_TEXTTYPE                    7
#define IDR_IRCTYPE                     8
#define IDR_PREFERENCES                 9
#define IDP_INVALID_TO_ADDRESS          10
#define IDP_INVALID_FROM_ADDRESS        11
#define IDP_NETWORK_ERROR               12
#define IDP_INVALID_MAIL_HEADERS        13
#define IDD_ABOUTBOX                    100
#define IDR_NEWMAILTYPE                 101
#define IDC_BIGICON                     103
#define IDD_RULERBAR                    103
#define ID_MIRROR_DISPLAY_FONT          104
#define IDI_EARTH                       121
#define IDD_SPLASH                      122
#define IDB_BTNTRI                      122
#define IDD_EXIT_APPLICATION            123
#define IDB_FILE                        134
#define IDR_GOPHERMENU                  139
#define IDR_GOPHEROUTPUT                140
#define IDR_HELPINFO                    141
#define IDD_GOPHER_SEARCH               143
#define IDD_TIP_OF_THE_DAY              144
#define IDI_AOL                         147
#define IDB_PLACES                      166
#define IDB_CHAT                        171
#define IDD_IRC_SEND_PRIVMSG            176
#define IDD_IRC_SEND_COMMAND            177
#define IDD_IRC_JOIN_CHANNEL            178
#define IDD_IRC_CONNECT                 179
#define IDD_IRC_CHANGE_NICKNAME         180
#define IDD_FTP_OPEN_WARNING            183
#define IDD_FINGER_ADDR                 184
#define IDD_DISCONNECT                  188
#define IDB_MINIINFO                    189
#define IDD_MAI_SETUP_1                 193
#define IDR_MAILBOXTYPE                 194
#define IDR_MESSAGETYPE                 195
#define IDR_MAILCOMPOSETYPE             196
#define IDR_NEWSAREATYPE                197
#define IDB_ERROR_ALERT                 200
#define IDD_EMAIL_DIALOG_BAR            202
#define IDB_INTERFOLDER                 213
#define IDB_INTERFILE                   214
#define IDB_AMERICA_ONLINE              216
#define IDB_COMPUSERVE                  217
#define IDB_PRODIGY                     218
#define IDB_GNN                         219
#define IDD_APP_GENERAL_PREFS           221
#define IDB_MINIEARTH                   223
#define IDI_ICON_TIP_OF_THE_DAY         225
#define IDD_GOPHER_SITE_PROPERTIES      237
#define IDD_NEWSGROUPS_SETUP            239
#define IDD_EMAIL_SETTINGS              240
#define IDD_ADD_NEWSGROUP               241
#define IDD_ARTSELTYPE_FORM             246
#define IDI_WINSOCK                     249
#define IDI_CHOL                        250
#define IDD_INTERNET_FINGER_PREFS       251
#define IDD_ADDRESS_BOOK                255
#define IDI_ADDRBOOK                    256
#define IDD_ADD_ADDRESS                 258
#define IDD_ARTICLE_AGE                 261
#define IDD_INETNAV_WELCOME             263
#define IDD_FTP_PROPS_GENERAL           264
#define IDD_FTP_USER_DIR                265
#define IDD_FLASHCONNECT_BEGIN          267
#define IDD_FLASHCONNECT_END            269
#define IDD_NEWS_COMPOSE_DIALOG_BAR     271
#define IDR_NEWSCOMPOSETYPE             273
#define IDC_INETNAV_NAME                274
#define IDI_WORLD                       276
#define IDB_WORLD                       277
#define IDD_OPEN_FTP_SITE               281
#define IDC_BACK                        292
#define IDW_TECHSUPPORT_DIALOG_BAR      298
#define IDD_TECHSUPPORT_DIALOG_BAR      300
#define IDD_GOPHER_OPTIONS              301
#define IDD_FINGER_OPTIONS              302
#define IDD_FTP_OPTIONS                 303
#define IDI_INTERFILE                   304
#define IDI_NEWSGROUP                   305
#define IDI_ICON1                       306
#define IDI_INTERFOLDER                 307
#define IDD_DOWNLOAD_COMPLETE           308
#define IDD_DOWNLOAD_FILE               309
#define IDD_CONNECT                     311
#define IDD_COMPMAIL_WIZ1               312
#define IDD_CHOOSE_RECIPIENT            313
#define IDD_OPEN_HELP_FILE              314
#define IDD_FTP_PREFS_ADVANCED          315
#define IDI_HELPBOOK                    321
#define IDI_RECYCLE                     322
#define IDB_MAILFILE                    327
#define IDD_FLASHCONNECT_ABORT          328
#define IDD_INTERNET_MAILBOXES          329
#define IDD_FTP_VIRUSES                 330
#define IDD_FTP_VIRUSCAN                331
#define IDD_FEEDBACK_WIZ1               332
#define IDD_ARTICLE_OPTIONS             335
#define IDC_HOST                        1000
#define IDC_SITE_NAME                   1000
#define IDC_SERVER                      1000
#define IDC_PERCENTTEXT                 1000
#define IDC_STATIC_LIGHTBULB            1000
#define IDC_USER                        1001
#define IDC_PORT_NUM                    1001
#define IDC_SITE_ADDRESS                1001
#define IDC_BAR                         1001
#define IDC_LOOKUP                      1002
#define IDC_FILES                       1002
#define IDC_HEADER                      1002
#define IDC_RULER                       1002
#define IDC_NICKNAME                    1002
#define IDC_SELECTOR                    1002
#define IDC_CLEAR                       1003
#define IDC_FOOTER                      1003
#define IDC_CHANNEL                     1003
#define IDC_PORT                        1003
#define IDC_INET_PREFS                  1004
#define IDC_CANCEL                      1004
#define ID_CHOOSE_FONT                  1004
#define IDC_HEADER_FILE                 1004
#define IDC_EDIT_TABS                   1004
#define IDC_NEW_CHANNEL                 1004
#define IDC_TITLE                       1004
#define IDC_HELP                        1005
#define IDC_HEADER_SYSTEM               1005
#define IDC_RECIPIENT                   1005
#define IDC_OUTPUT                      1006
#define ID_WORD_WRAP                    1006
#define IDC_FOOTER_FILE                 1006
#define IDC_MESSAGE                     1006
#define IDC_FOOTER_SYSTEM               1007
#define IDC_NEW_NICKNAME                1007
#define IDC_FORM_ICON                   1008
#define IDC_CONNECT                     1008
#define IDC_COMMAND                     1008
#define IDC_NIC                         1009
#define IDC_DISCONNECT                  1009
#define IDC_CHANGE_REMOTE_DIRECTORY     1010
#define IDD_SET_TABSTOPS                1010
#define IDC_GET                         1011
#define IDC_PUT                         1012
#define IDC_APP_PREFS                   1014
#define IDC_CHANGE_DIRECTORY_UP         1014
#define IDC_USER_ID                     1019
#define IDC_PASSWORD                    1020
#define IDC_WELCOME_MSG                 1022
#define IDC_MAIL_MANAGER                1033
#define IDC_HELPINFO                    1034
#define IDC_FINGER                      1035
#define IDC_WHOIS                       1036
#define IDC_USER_NAME                   1036
#define IDC_FTP                         1037
#define IDC_USER_COMPANY                1037
#define IDC_GOPHER                      1038
#define psh15                           0x040e
#define IDC_USENET_NEWS                 1039
#define IDC_SEARCH                      1039
#define IDC_IRC_CHAT                    1040
#define IDC_MENU_LIST                   1040
#define chx1                            0x0410
#define IDC_PREFS                       1041
#define IDC_SITE_TITLE_LABEL            1043
#define IDC_SITE_ADDR_LABEL             1044
#define IDC_SELECTOR_LABEL              1045
#define IDC_PORT_LABEL                  1046
#define IDC_HEADER_LABEL                1047
#define IDC_QUERY                       1049
#define IDC_DIRECTORY                   1050
#define IDC_HELPINF                     1052
#define IDC_APP_ABOUT                   1053
#define IDC_HELP_CONTENTS               1054
#define IDC_TECH_SUPPORT                1055
#define IDC_INET_CLIENTS_HELP           1056
#define IDC_SEARCH_HELP                 1057
#define IDC_USER_INF                    1070
#define IDC_ADDRESS                     1073
#define IDC_DONT_SHOW_AGAIN             1075
#define IDC_MAIL_ADDRESS                1078
#define IDC_SMTP_ADDRESS                1079
#define IDC_POP3_ADDRESS                1080
#define IDC_MAILBOX_TITLE               1081
#define IDC_MAILBOX_CHECK               1082
#define IDC_GROUP_MANAGER               1082
#define IDC_MAILBOX_SETUP               1083
#define IDC_NEWSGROUPS_SETUP            1083
#define IDC_MAILBOX_COMPOSE             1084
#define IDC_COMPOSE_ARTICLE             1084
#define IDC_MESSAGE_LIST                1085
#define IDC_MAIL_ADDRESS_BOOK           1085
#define IDC_NUM_MESSAGES                1086
#define stc1                            0x0440
#define stc2                            0x0441
#define stc3                            0x0442
#define stc4                            0x0443
#define IDC_MESSAGE_SUBJECT             1093
#define IDC_MESSAGE_TO                  1094
#define IDC_MESSAGE_CC                  1095
#define IDC_MESSAGE_BCC                 1096
#define IDC_COMPANY                     1103
#define lst1                            0x0460
#define lst2                            0x0461
#define IDC_START_ONLINE                1124
#define IDC_SHOW_MAIN_MENU              1125
#define cmb1                            0x0470
#define cmb2                            0x0471
#define IDC_CONFIRM_EXIT                1139
#define IDC_SHOW_TIPS                   1141
#define IDC_SHOW_TIPS_INET              1142
#define IDC_WALKTHROUGH                 1150
#define IDC_NO_WALKTHROUGH              1151
#define edt1                            0x0480
#define IDC_SITE_SERVER                 1153
#define IDC_SITE_PATH                   1154
#define IDC_SITE_PORT                   1157
#define IDC_NEWSGROUPS_LIST             1158
#define ID_NEXT_TIP                     1159
#define ID_PREV_TIP                     1160
#define IDC_TIP_TEXT_EDIT               1161
#define IDC_SHOW_TIP_AT_STARTUP         1162
#define IDC_NNTP_HOST                   1164
#define IDC_EMAIL_ADDRESS               1169
#define IDC_USERID                      1171
#define IDC_NEWSGROUP                   1178
#define IDC_DOWNLOAD_GROUPS             1180
#define IDC_ARTICLES_LIST               1183
#define IDC_ARTICLES_LABEL              1184
#define IDC_WINDOW_REFRESH              1189
#define IDC_ASK_FINGER_ADDR             1190
#define IDC_REPORT_QUERY_PROGRESS       1191
#define IDC_AUTO_SAVE                   1193
#define IDC_AUTO_PRINT                  1194
#define IDC_CONFIRM_DISCONNECT          1195
#define IDC_CONFIRM_SIGNOFF             1196
#define IDC_ADDRESS_LIST                1205
#define IDC_ADD_ADDRESS                 1206
#define IDC_REMOVE_ADDRESS              1207
#define IDC_TO_ADDRESS                  1208
#define IDC_CC_ADDRESS                  1209
#define IDC_BCC_ADDRESS                 1210
#define IDC_SIGNATURE                   1217
#define IDC_AGE_DAYS                    1218
#define IDC_AGE_HOURS                   1219
#define IDC_AGE_MINUTES                 1220
#define IDC_AGE_SECONDS                 1221
#define IDC_ARTICLE_AGE                 1222
#define IDC_GROUPS_LIST                 1231
#define IDC_ARTICLE_SUBJECT             1233
#define IDC_ARTICLE_NEWSGROUPS          1234
#define IDC_ARTICLE_DISTRIBUTION        1235
#define IDC_ARTICLE_FOLLOWUP_TO         1238
#define IDC_USE_ANON_FTP                1239
#define IDC_INFO                        1244
#define IDC_SIG_LABEL                   1245
#define IDC_SET_DOWNLOAD_DIR            1251
#define IDC_DISPLAY_ON_DOWNLOAD         1252
#define IDC_GOPHER_DOC_DIR              1253
#define IDC_BROWSE                      1254
#define IDC_DIRBROWSE                   1255
#define IDC_RQP                         1257
#define IDC_ASK_ADDR                    1258
#define IDC_OPEN_ASCII                  1262
#define IDC_OPEN_BIN                    1263
#define IDC_DECOMP_SEF                  1264
#define IDC_INSTALL_SOFTWARE            1265
#define IDC_FILE_DOWNLOADED             1267
#define IDC_WAIT_TEXT                   1269
#define IDC_FILE_PATH                   1271
#define IDC_FILE_BYTES                  1272
#define IDC_FILE_NAME                   1273
#define IDC_SUBJECT                     1281
#define IDC_CHOOSE                      1284
#define IDC_TO                          1285
#define IDC_CC                          1286
#define IDC_BCC                         1287
#define IDC_OPEN_CONTENTS               1288
#define IDC_OPEN_SEARCH                 1289
#define IDC_WARN_OPEN_BIN               1295
#define IDC_OPEN_WARN                   1297
#define IDC_ADVANCED                    1298
#define IDC_VIRUSES                     1299
#define IDC_SETTINGS                    1300
#define IDC_DOWNLOAD_DIR                1303
#define IDC_UPLOAD_DIR                  1304
#define IDC_ADD                         1307
#define IDC_REMOVE                      1308
#define IDC_MESSAGE_BOARD               1309
#define IDC_OPEN_SITE                   1310
#define IDC_GOPHER_INFO                 1311
#define IDC_GOPHER_SEARCH               1312
#define IDC_EDIT1                       1313
#define IDC_STARTUP_CHECK_MAIL          1314
#define IDC_MAILBOX_LIST                1318
#define IDC_ADD_MAILBOX                 1319
#define IDC_REMOVE_MAILBOX              1320
#define IDC_SET_DEFAULT_MAILBOX         1322
#define IDC_DEFAULT_MAILBOX             1323
#define IDC_VIRUSCAN_PATH               1325
#define IDC_DISCLAIMER                  1327
#define IDC_OPEN_TYPE                   1332
#define IDC_SCAN                        1333
#define IDC_SEND_CONFIRM                1334
#define IDC_SEND_CLOSE                  1335
#define IDC_SETUP_NEW_MAILBOX           1339
#define IDC_ASKSTAFF                    1340
#define IDC_SUGGESTION_BOX              1341
#define IDC_ISP_TECH_SUPPORT            1342
#define IDC_SHOW_WINDOW                 1343
#define IDC_FEEDBACK_WIZARD             1344
#define IDC_SHOW_WIN                    1344
#define IDC_NAV_1                       1345
#define IDC_NAV_2                       1346
#define IDC_NAV_3                       1347
#define IDC_NAV_4                       1348
#define IDC_NAV_5                       1349
#define IDC_EASE_1                      1350
#define IDC_FEATURES_ADD                1350
#define IDC_EASE_2                      1351
#define IDC_FEATURES_DELETE             1351
#define IDC_EASE_3                      1352
#define IDC_EASE_4                      1353
#define IDC_OPEN_ON_DOWNLOAD            1353
#define IDC_EASE_5                      1354
#define IDC_SHOW_SAVE_AS                1354
#define IDC_QUALITY_1                   1355
#define IDC_QUALITY_2                   1356
#define IDC_NOTIFY_ARRIVE               1356
#define IDC_QUALITY_3                   1357
#define IDC_NOTIFY_LEAVE                1357
#define IDC_QUALITY_4                   1358
#define IDC_QUALITY_5                   1359
#define IDC_LOCAL_HOST                  1359
#define IDC_IRC_SERVER                  1360
#define IDC_ARTICLE_DISPLAY             1364
#define IDC_ARTICLE_FULL                1365
#define IDC_ARTICLE_BODY                1366
#define IDC_NEWS_SERVER                 1369
#define IDC_NEWS_ADDRESS                1370
#define IDC_NEWSGROUPS                  1371
#define IDC_DISTRIBUTION                1372
#define IDC_FOLLOWUP_TO                 1373
#define IDC_TIME_OUT                    1376
#define FILEOPENORD                     1536
#define IDP_ERR_GET_PRINTER_DC          4000
#define IDP_ERR_GET_DEVICE_DEFAULTS     4001
#define IDD_PAGE_SETUP                  30742
#define IDD_FTP_CONNECT                 30743
#define IDD_FTP_WELCOME                 30744
#define IDD_GOPHER_CONNECT              30747
#define IDD_FTP_AOL_DIRECTORY           30748
#define IDD_PERCENT                     30749
#define IDD_MAI_SETUP_2                 30751
#define IDD_MAI_SETUP_3                 30752
#define IDD_MAI_SETUP_4                 30753
#define IDD_MAI_SETUP_7                 30754
#define IDD_NEW_MAILBOX                 30755
#define IDD_MAIL_LOGON                  30756
#define IDD_MAIL_COMPOSE_DIALOG_BAR     30757
#define IDD_USER_INFORMATION            30758
#define IDR_GROUPMAN                    30761
#define IDR_ARTSELTYPE                  30762
#define IDD_MAI_SETUP_6                 30762
#define IDD_NNTPARTICLE_DIALOG_BAR      30763
#define IDR_ARTICLETYPE                 30763
#define IDD_INTERNET_WHOIS_PREFS        30764
#define IDD_MAIL_SIGNATURE              30765
#define IDD_MAI_SETUP_5                 30766
#define IDD_NEWS_SIGNATURE              30767
#define IDD_FTP_PROPS_FILES             30768
#define IDD_WHOIS_OPTIONS               30769
#define IDD_FTP_PERCENT                 30770
#define IDD_DISCONNECTED                30771
#define IDD_COMPMAIL_WIZ2               30772
#define IDD_COMPMAIL_WIZ3               30773
#define IDD_COMPMAIL_WIZ4               30774
#define IDD_COMPMAIL_WIZ5               30775
#define IDD_COMPMAIL_WIZ6               30776
#define IDD_INTERNET_FTP_PREFS          30777
#define IDD_APP_AREAS_PREFS             30778
#define IDR_GOPHCENTERTYPE              30779
#define IDD_MAIL_USER_INFORMATION       30780
#define IDD_INTERNET_MAIL_PREFS         30781
#define IDR_ASKSTAFF                    30782
#define IDD_ISP_TECHSUPPORT_DIALOG_BAR  30783
#define IDD_SUGGESTION_BOX_BAR          30784
#define IDD_FEEDBACK_WIZ2               30785
#define IDD_FEEDBACK_WIZ3               30786
#define IDD_FEEDBACK_WIZ4               30787
#define IDD_FEEDBACK_WIZ5               30788
#define IDD_INTERNET_GOPHER_PREFS       30789
#define IDD_INTERNET_CHAT_PREFS         30790
#define IDD_INTERNET_NEWS_PREFS         30791
#define IDD_NWS_SETUP_1                 30792
#define IDD_NWS_SETUP_2                 30793
#define IDD_NWS_SETUP_3                 30794
#define IDD_NWS_SETUP_4                 30795
#define IDD_COMPNEWS_WIZ6               30796
#define IDD_COMPNEWS_WIZ5               30797
#define IDD_COMPNEWS_WIZ4               30798
#define IDD_COMPNEWS_WIZ3               30799
#define IDD_COMPNEWS_WIZ2               30800
#define IDD_COMPNEWS_WIZ1               30801
#define IDB_FOLDER                      30990
#define IDB_LINK                        30991
#define IDB_BLANK_FILE                  30992
#define IDB_SEARCH                      30993
#define IDB_OPEN_FOLDER                 30994
#define ID_PAGE_SETUP                   32769
#define ID_CHOOSE_PRINT_FONT            32770
#define ID_LOOKUP                       32771
#define ID_LOOKUP_CANCEL                32773
#define ID_SCROLL_PAGE_DOWN             32774
#define ID_SCROLL_PAGE_UP               32775
#define ID_SCROLL_LINE_DOWN             32776
#define ID_SCROLL_LINE_UP               32777
#define ID_LOOKUP_NIC                   32778
#define ID_WINDOW_REFRESH               32779
#define ID_SITE_CHG_DIR                 32780
#define ID_SITE_CHG_DIR_UP              32781
#define ID_SITE_CONNECT                 32782
#define ID_SITE_DISCONNECT              32783
#define ID_TRANSFERS_DOWNLOAD           32784
#define ID_TRANSFERS_UPLOAD             32785
#define ID_NEW_TEXT                     32788
#define ID_VIEW_RULER                   32789
#define ID_PLACES_POST_OFFICE           32790
#define ID_PLACES_PREFERENCES           32791
#define ID_PLACES_HELPINFO              32792
#define ID_PLACES_FINGER                32793
#define ID_PLACES_WHOIS                 32794
#define ID_PLACES_FTP_CLIENT            32795
#define ID_PLACES_CHAT_CENTER           32796
#define ID_PLACES_NEWSGROUPS            32797
#define ID_PLACES_GOPHER_CENTER         32798
#define ID_GOPHER_SITE                  32799
#define ID_GOPHER_VIEW                  32800
#define ID_GOPHER_SEARCH                32801
#define ID_GOPHER_HELP                  32802
#define ID_WINDOW_REMEMBER              32804
#define ID_WINDOW_CLOSE_ALL             32805
#define ID_PLACES_SIGN_OFF              32806
#define ID_PLACES_SIGN_ON               32807
#define ID_TRANSFERS_LINK               32809
#define ID_CANCEL_CALL                  32813
#define ID_CHAT_JOIN_GROUP              32814
#define ID_CHAT_CHANGE_GROUP            32815
#define ID_CHAT_CHANGE_NICKNAME         32816
#define ID_CHAT_SEND_PRIVMSG            32817
#define ID_CHAT_SEND_COMMAND            32818
#define ID_SITE_CHG_USER_DIR            32819
#define ID_MAILBOX_CHECK                32820
#define ID_MAILBOX_COMPOSE              32821
#define ID_MAILBOX_SETUP                32822
#define ID_MAIL_DISPLAY_MESSAGE         32825
#define ID_MAIL_REPLY                   32826
#define ID_MAIL_SEND                    32827
#define ID_MAIL_DELETE                  32828
#define ID_MESSAGE_FIRST                32829
#define ID_MESSAGE_PREV                 32830
#define ID_MESSAGE_NEXT                 32831
#define ID_MESSAGE_LAST                 32832
#define ID_MAILBOX_LOGON                32833
#define ID_GOPHER_SITE_PROPERTIES       32836
#define ID_NEWSGROUPS_SETUP             32837
#define ID_MAIL_SETTINGS                32838
#define ID_GROUP_OPEN                   32839
#define ID_GROUP_ADD                    32841
#define ID_GROUP_REMOVE                 32842
#define ID_ARTICLES_OPEN                32843
#define ID_ARTICLE_OPENARTICLE          32844
#define ID_ARTICLE_OPEN                 32845
#define ID_ARTICLE_ADD                  32847
#define ID_ARTICLE_REPLY                32849
#define ID_TIP_OF_DAY                   32850
#define ID_WINDOW_ARTICLE_REFRESH       32851
#define ID_ARTICLE_REPLY_EMAIL          32852
#define ID_MAIL_ADDRESS_BOOK            32853
#define ID_ARTICLE_OPTIONS              32854
#define ID_ARTICLE_SIGNATURE            32855
#define ID_ARTICLE_FOLLOWUP             32856
#define ID_ARTICLE_FIRST                32857
#define ID_ARTICLE_PREVIOUS             32858
#define ID_ARTICLE_NEXT                 32859
#define ID_ARTICLE_LAST                 32860
#define ID_ARTICLE_AGE                  32862
#define ID_FTP_VIEW_PROPERTIES          32863
#define ID_MAIL_SIGNATURE               32865
#define ID_ARTICLE_SEND                 32866
#define ID_MAILBOX_COMPOSE_OFFLINE      32868
#define ID_ARTICLE_ADD_OFFLINE          32869
#define ID_FINGER_OPTIONS               32870
#define ID_GOPHER_OPTIONS               32871
#define ID_SITE_DOWNLOAD_FILE           32872
#define ID_HELP_SEARCH                  32873
#define ID_GOPHER_MESSAGE_BOARD         32874
#define ID_GOPHER_OPEN_SITE             32875
#define ID_GOPHER_INFO                  32876
#define ID_FILE_DELETE                  32877
#define ID_INTERNET_MAILBOXES           32878
#define ID_INDICATOR_OFFLINE            59140
#define IDW_MAIL_COMPOSE_BAR            0xE822
#define IDW_NEWS_COMPOSE_DIALOG_BAR     0xE823
#define IDW_EMAIL_COMMAND_BAR           0xE830
#define IDW_NNTPARTICLE_COMMAND_BAR     0xE831
#define AFX_IDS_SCNEXT                  61188
#define AFX_IDS_SCPREV                  61189
#define IDP_SIGNON_FAILED               61216
#define IDP_INFO_NEEDED                 61217
#define IDP_NOCONNECT_HOST              61218
#define IDS_CONNECTING                  61219
#define IDS_RESOLVING_HOSTNAME          61220
#define IDS_DS_INTERNIC_NET             61221
#define IDS_SENDING_REQUEST             61222
#define IDS_RECEIVING_RESPONSE          61223
#define IDP_NOCONNECT_NIC               61224
#define IDS_FTP_CONNECTED_SUCCESSFUL    61225
#define IDP_FTP_LOGON_FAILED            61226
#define IDP_FTP_INFO_NEEDED             61227
#define IDP_ERROR_DISCONNECT            61228
#define IDP_LIST_FAILED                 61229
#define IDP_TRANSFER_COMPLETE           61230
#define IDP_FTP_NOFILESLIST             61231
#define IDP_FTP_NO_FILES                61231
#define IDP_NOCONNECT_POP3_HOST         61232
#define IDP_NOCONNECT_SMTP_HOST         61233
#define IDP_INVALID_POP3_PASSWORD       61234
#define IDP_INVALID_EMAIL_ADDRESS       61235
#define IDP_NOCONNECT_POP3_DELETE_HOST  61237
#define IDP_INVALID_USERID              61238
#define AFX_IDP_INVALID_FORMAT          61728
#define IDP_ACCESS_DENIED               61735
#define IDP_AREA_NO_AVAILABLE           61989
#define IDS_GOPHER_SERVER               61990
#define IDS_GOPHER_TITLE                61991
#define IDP_GOPHER_NODOC                61992
#define IDP_INETNAV_SIGN_ON             61993
#define IDS_GOPHER_SEARCH               61994
#define IDP_SEARCH_INFO_NEEDED          61995
#define IDP_ENTER_HELP_AREA             61996
#define IDP_EXIT_HELP_AREA              61997
#define IDP_SOCKET_WSAEWOULDBLOCK       61998
#define IDP_SOCKET_WSAENETRESET         61999
#define IDP_SOCKET_WSAENETDOWN          62001
#define IDP_SOCKET_WSAENETERROR         62002
#define IDP_FAILED_TO_OPEN_MAILBOX      62003
#define IDP_GOPHER_NOSEARCH             62004
#define IDP_FAILED_TO_CREATE_MAILBOX    62005
#define IDP_SOCKET_WSAENOTSOCK          62006
#define IDP_SETUP_NEW_MAILBOX           62008
#define IDP_NOCONNECT_NNTP_HOST         62009
#define IDP_ERRSPACE_NEWSGROUPS_LIST    62010
#define IDP_FAILED_GET_INFO             62011
#define IDP_CONNECTION_BUSY             62012
#define IDP_FAILED_CREATE_SOCKET        62013
#define IDP_SOCKET_WSAEADDRINUSE        62014
#define IDP_SOCKET_WSAECONNABORTED      62015
#define IDP_SOCKET_WSAECONNREFUSED      62016
#define IDP_SOCKET_WSAECONNRESET        62017
#define IDP_SOCKET_WSAEDESTADDRREQ      62018
#define IDP_SOCKET_WSAEHOSTUNREACH      62019
#define IDP_SOCKET_WSAEMFILE            62020
#define IDP_SOCKET_WSAENOBUFS           62021
#define IDP_SOCKET_WSAETIMEDOUT         62022
#define IDP_SOCKET_WSAHOST_NOT_FOUND    62023
#define IDP_SOCKET_WSASYSNOTREADY       62024
#define IDP_SOCKET_WSANOTINITIALISED    62025
#define IDP_SOCKET_WSANO_DATA           62026
#define IDP_SOCKET_WSANO_RECOVERY       62027
#define IDP_SOCKET_WSATRY_AGAIN         62028
#define IDP_SOCKET_WSAVERNOTSUPPORTED   62029
#define IDP_NEWSGROUP_EMPTY             62030
#define IDP_FTP_ACCESS_DENIED           62031
#define IDP_FLASHCONNECT_ABORTED        62032
#define IDP_NEWSGROUP_VALID             62033
#define IDP_NEWSGROUP_INVALID           62034
#define IDP_FAILED_RETRIEVE_ARTICLE     62035
#define IDP_INVALID_SIGNATURE           62036
#define IDP_NNTP_ERROR_412              62037
#define IDP_NNTP_ERROR_423              62038
#define IDP_NNTP_ERROR_430              62039
#define IDP_DISCONNECT_INFO_CHANGED     62040
#define IDP_NNTP_ERROR_400              62041
#define IDP_NNTP_ERROR_500              62042
#define IDP_NNTP_ERROR_501              62043
#define IDP_NNTP_ERROR_502              62044
#define IDP_NNTP_ERROR_503              62045
#define IDP_ARTICLE_NOT_POSTED          62046
#define IDP_ARTICLE_POST_DENIED         62047
#define IDP_ARTICLE_INVALID_HEADERS     62048
#define IDP_ARTICLE_FAILED_SEND_HEADERS 62049
#define IDP_SETUP_NEWSGROUPS            62051
#define IDP_TECHSUPPORT_SETUP_NEW_MAILBOX 62052
#define IDP_ARTICLE_POST_SUCCESS        62053
#define IDP_INVALID_ARTICLE             62054
#define IDP_FAILED_OPEN_WINDOW          62055
#define IDS_REQUESTING_ATTENTION        62056
#define IDS_TALKING_TO_SERVER           62057
#define IDS_OPENING_DATA_CONNECTION     62059
#define IDS_RECEIVING_LIST              62060
#define IDS_WAITING_RESPONSE            62061
#define IDS_REQUESTING_DIRECTORY        62062
#define IDS_DELIVERING_MAIL             62063
#define IDS_DELIVERING_NEWS             62064
#define IDS_REQUESTING_MAIL             62065
#define IDS_RECEIVING_MESSAGE           62066
#define IDS_RECEIVING_ARTICLE           62067
#define IDP_FAILED_PREPARE_FOLLOWUP     62068
#define IDP_FAILED_MEMORY_SOCKET_ALLOC  62069
#define IDP_FTP_RECONNECT               62070
#define IDP_DOWNLOAD_ABORTED            62071
#define IDP_PSEUDOUSER_INTRO            62072
#define IDS_PRIVMSG_ARRIVED             62073
#define IDP_TOADDRREQ                   62074
#define IDP_SUBJECT_REQ                 62075
#define IDP_TO_NO_SPACES                62076
#define IDP_CC_NO_SPACES                62077
#define IDP_BCC_NO_SPACES               62078
#define IDP_SHELL_ONE_COPY              62079
#define IDP_FILE_NOT_FOUND              62080
#define IDP_PATH_NOT_FOUND              62081
#define IDP_DYNLINKFAILED               62082
#define IDP_SEPARATE_DATA_SEGS          62083
#define IDP_INSUFFICIENT_MEMORY         62084
#define IDS_DOWNLOAD_MESSAGE            62085
#define IDS_DL_WAIT_TEXT                62086
#define IDS_UL_WAIT_TEXT                62087
#define IDS_DISCONNECTED_TEXT           62088
#define IDS_WAITING_DATA_CONNECTION     62089
#define IDS_UPLOAD_MESSAGE              62090
#define IDS_ACCESSING_MAILBOX           62091
#define IDS_CHECKING_PASSWORD           62092
#define IDS_DELETING_MESSAGE            62093
#define IDS_CONNECTING_TO_INTERNET      62094
#define IDP_GOPHER_FAILED_FIND_INFO     62095
#define IDS_PROCESSING_TO               62096
#define IDS_PROCESSING_CC               62097
#define IDS_PROCESSING_BCC              62098
#define IDS_SENDING_TO                  62099
#define IDS_SENDING_CC                  62100
#define IDS_SENDING_BCC                 62101
#define IDP_MAKE_MAILBOX_DEFAULT        62102
#define IDP_MAILBOX_EXISTS              62103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1377
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
