@ECHO ีออออออออออออออออออออออออออออออออออออออออออธ
@ECHO ณ                                          ณ
@ECHO ณ  R o b o   H E L P                  ฐ ฐ  ณ
@ECHO ณ ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ              ฐ ฐ ฐ ฐ ณ
@ECHO ณ  Make Help Project              ฐ ฐฐฐ ฐ ฐณ
@ECHO ณ                                  ฐ ฐฐฐ  ฐณ
@ECHO ณ                                 ฐ ฐ  ฐฐ  ณ
@ECHO ณ                                  ฐ ฐ  ฐฐ ณ
@ECHO ณ                                       ฐฐฐณ
@ECHO ณ B L U E   S K Y   S O F T W A R E      ฐฐณ
@ECHO ณ                                        ฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐฐฐฐฐฐฐณ
@ECHO ณฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐณ
@ECHO ิออออออออออออออออออออออออออออออออออออออออออพ
@ECHO Batch File: C:\APPS\INTERNET\INETNAV\HLP\README\RHHC.BAT
@ECHO Project File: C:\APPS\INTERNET\INETNAV\HLP\README\README.HPJ
del README.ERR
set TMP=C:\WINDOWS\TEMP
if (%TMP%)==() set TMP=%TEMP%
if (%TMP%)==() set TMP=C:\

C:\ROBOHELP\HCP.EXE README.HPJ
copy README.HLP C:\APPS\INTERNET\INETNAV\HLP
copy README.HLP C:\INETNAV


